# -*- coding: utf-8 -*-
"""Number Guessing Gamne.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m3te1F3b61HXMUBcc0_wLDVjdDhqncJb
"""

# Simple Number Guessing Game
import random

# Random number (1 to 10)
number = random.randint(1, 10)

print("Number Guessing Game")
print("Guess a number between 1 and 10")

#Take user input
user_guess = int(input("Enter Your Number:"))

#Check users number
if user_guess == number:
  print("Congratulations! you gussed it right")
else:
  print(f"Wrong! The correct Number was {number}")